# Generated by Django 2.0.5 on 2019-08-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190708_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='categoty',
            field=models.CharField(choices=[('story', 'Story'), ('report', 'Reports'), ('poems', 'Poems'), ('art', 'Art')], default='report', max_length=100),
        ),
    ]
